### ISSUE TITLE
Tubby Toast and Custard not edible.

### ISSUE THREAD

**Issue by GuichoSax** [Rexbas/Teletubbies-Mod#13]
Minecraft Version: 1.15.2
Forge Version: 31.1.0
Teletubbies mod version: Teletubbies 6.0.0
Java Version: 8 Update 241 (64 bit)
Operating System (OS): Windows 10 Home 64-bit.
Aternos multiplayer (private) server.

Issue Description:
You can't eat Tubby Custard or Tubby Toast

Steps to reproduce:
+    Craft a Tubby Toast Machine or Tubby Custard Machine.
+    Have your Tubby Bowl filled with Tubby Custard and get your Tubby Toast from the machine or from a zombie Teletubbies as a dropped loot.
+    Try to eat either with the right-click
+    Nothing will happen at all, as if you were right clicking with a wood stick on your hand.

Additional Information:
+    I've removed every other mod in the game and tested, both Custard and Toast still can't be edible.
+   We also checked with the mod "Apple Skin" (which tells you how much hunger and saturation will fill each food) and, when hovering the mouse over the Custard or Toast, it won't show any edible information as if it were just another item (no food).
+   Tried with main right hand and left hand of the player.

If you need me to test anything or I've missed additional information, please let me know :) thank you very much in advance for the help!

**Comment by Rexbas** [comment]
Thanks for reporting, should be fixed in 1.14.4-5.2.2 and 1.15.2-6.0.1

**Comment by GuichoSax** [comment]
Thanks for taking a look Rexbas!
Sorry to bring the bad news but those, when they are already "chewable" they are still not actually edible.

You see, you hold the right click to eat both but the player keeps:
1) Making the chewing sound, 
2) Spitting food particles
3) Walking slowly 
but it never actually eats them. :(
Could you kindly re-open this issue?

Also, I'm seeing with the Apple Skin mod that:
1) The Tubby Toast gives 2 hunger points and 10 saturation points!!
2) The Tubby Custard gives 4 hunger points and 20 saturation points!!?! 
Is that intended? It's way too op! D:

Thank you very much again and sorry for all the trouble! <3

**Comment by Rexbas** [comment]
That is weird. It works for me. Could you try it on a clean world with only teletubbies mod in singleplayer?

**Comment by GuichoSax** [comment]
Ah, so it seems my dumb ass decided to forget to update the mod also on the Aternos server and I only did it on the client haha sorry about that, yes, it's working perfectly! Please disregard half of what I write above.

I say half because I can also confirm the latter, that the Tubby Toast and Custard they give 2 hunger points and 4 hunger points respectively but they also give 10 and 20 saturation points respectively :O that is excessive and demotivate us from taking them to expeditions as it feels like cheating 'cause they fill up almost instantly 16 health points (8 hearts) and, well, they are pretty much free to get with the machines. 
Is that the way they are purposely programmed or is that an error?

If that is intended then it's ok :D we can also eat them only at home no problem! we want to give you the less trouble possible. Thank you very much for your kind responses always.

**Comment by Rexbas** [comment]
It was an error. I never really understood the saturation. It is indeed a little bit overpowered. In the next update it will be reduced to 2 and 4 saturation points. It will release soon.
